baseURL = 'https://viueek.github.io/'
languageCode = 'ja'
title = '記録'
theme = 'PaperMod'

[params]
  math = true

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "アーカイブ"
    url = "/archives/"
    weight = 10

    buildFuture = true